//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegApp
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class tbl_User
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Gender { get; set; }
        public Nullable<bool> isIntrestedInJava { get; set; }
        public Nullable<bool> isIntrestedInCSharp { get; set; }
        public Nullable<bool> isIntrestedInPython { get; set; }
        public Nullable<int> cityId { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public SelectList CityList { get; set; }

        public virtual tbl_city tbl_city { get; set; }
    }
}
